### ISSUE TITLE
CSV Data Config

### ISSUE THREAD

**Issue by codedude10** [kulya/jmeter-gradle-plugin#17]
Hi, 

I have a JMeter test plan which uses the included CSV Data Config in the test plan. When I run via gradle I get the following errors. This is AFTER I added the /ext and /junit to my gradle/libs folder to fix those errors, as mentioned in issue #9. 

Any ideas? Log is below.

Thank you. 

2013/04/18 14:03:52 WARN  - jmeter.testbeans.BeanInfoSupport: Localized strings not available for bean class org.apache.jmeter.config.CSVDataSet java.util.MissingResourceException: Can't find bundle for base name org.apache.jmeter.config.CSVDataSetResources, locale en_US
    at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1499)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1322)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:796)
    at org.apache.jmeter.testbeans.BeanInfoSupport.<init>(BeanInfoSupport.java:111)
    at org.apache.jmeter.config.CSVDataSetBeanInfo.<init>(CSVDataSetBeanInfo.java:45)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at java.lang.Class.newInstance0(Class.java:374)
    at java.lang.Class.newInstance(Class.java:327)
    at com.sun.beans.finder.InstanceFinder.instantiate(InstanceFinder.java:96)
    at com.sun.beans.finder.InstanceFinder.find(InstanceFinder.java:66)
    at java.beans.Introspector.findExplicitBeanInfo(Introspector.java:436)
    at java.beans.Introspector.<init>(Introspector.java:386)
    at java.beans.Introspector.getBeanInfo(Introspector.java:161)
    at org.apache.jmeter.testbeans.TestBeanHelper.prepare(TestBeanHelper.java:67)
    at org.apache.jmeter.threads.TestCompiler.trackIterationListeners(TestCompiler.java:160)
    at org.apache.jmeter.threads.TestCompiler.subtractNode(TestCompiler.java:130)
    at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:978)
    at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:975)
    at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:959)
    at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:517)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:266)
    at java.lang.Thread.run(Thread.java:722)

2013/04/18 14:03:52 INFO  - jmeter.threads.JMeterThread: Thread started: PricingAPI 1-1 
2013/04/18 14:03:52 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NullPointerException
    at org.apache.jmeter.config.CSVDataSetBeanInfo.getShareModeAsInt(CSVDataSetBeanInfo.java:102)
    at org.apache.jmeter.config.CSVDataSet.iterationStart(CSVDataSet.java:113)
    at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:387)
    at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:379)
    at org.apache.jmeter.control.GenericController.next(GenericController.java:144)
    at org.apache.jmeter.control.LoopController.next(LoopController.java:108)
    at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:75)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268)
    at java.lang.Thread.run(Thread.java:722)

**Comment by Niravkumar-Patel** [comment]
Hey, I have been through all the above comment.. I had same issue and its been resolved by commenting upgrade_properties file in jmeter properties. 
Is it ok if I added the /ext and /junit to my gradle/libs folder to fix those errors, as mentioned in issue #9 and #5.? These will be the blank folder.

**Comment by djangofan** [comment]
As far as issue #9 goes, if you launch Jmeter 2.13 using the method I prepared in my GitHip repo, I doubt you would have any reason to add a /ext  or /junit folder to your Jmeter: 
https://github.com/djangofan/launch-jmeter
If you look at the build.gradle in the above repo, there is a mechanism to include whatever versions of any 3rd party libraries that you like.   It is fully tested and vetted for version 1.3.4-2.13 of jmeter-gradle-plugin .
