### ISSUE TITLE
Support Gradle 2.0

### ISSUE THREAD

**Issue by RoryStraubel** [kulya/jmeter-gradle-plugin#30]
Gradle has recently upgraded to version 2.0 with some important updates. This makes the jmeter plugin impossible to install. Thanks.

**Comment by foragerr** [comment]
Are you guys talking about the bundled gradle wrapper version?

**Comment by staleks** [comment]
No.

I have downloaded latest Gradle version 2.3.

This is the build script:

```
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath "com.github.kulya:jmeter-gradle-plugin:1.3.1-2.6"
	}
}

apply plugin: 'jmeter'

apply plugin: 'java'
apply plugin: 'eclipse'

sourceCompatibility = 1.8
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testCompile 'junit:junit:4.12'
}

jmeterRun.configure {
	jmeterTestFiles = [file("src/test/jmeter/test1.jmx")]
}
```

And here is the error:

```
A problem occurred evaluating root project 'gradle-jmeter'.
> Failed to apply plugin [id 'jmeter']
   > Could not find method add() for arguments [jmeterEditor, class com.github.kulya.gradle.plugins.jmeter.JmeterRunGuiTask] on task set.
```

I am not using task wrapper, just plain old gradle command from command line.


Any help would be appreciated.

**Comment by foragerr** [comment]
Can you please try with 1.3.2-2.6 as well?

**Comment by staleks** [comment]
Hi, I will,

but that version I don't see as released version :)

**Comment by foragerr** [comment]
It is.
http://mvnrepository.com/artifact/com.github.kulya/jmeter-gradle-plugin

While you're at it, you should up your jmeter version as well :)

**Comment by staleks** [comment]
Ok, now we are moving :)

I see that new version is uploaded to centra M2 repo. 

But this version is not in github:
https://github.com/kulya/jmeter-gradle-plugin/releases


Or maybe I am somewhere wrong?

Anyway, now I have different error when I run
```
$ gradle jmeterRun

Starting Build
Settings evaluated using empty settings script.
Projects loaded. Root project using build file '/home/astoisavljevic/work-home/gradle-jmeter/workspace/gradle-jmeter/build.gradle'.
Included projects: [root project 'gradle-jmeter']
Evaluating root project 'gradle-jmeter' using build file '/home/astoisavljevic/work-home/gradle-jmeter/workspace/gradle-jmeter/build.gradle'.
All projects evaluated.
Selected primary task 'jmeterRun' from project :
Tasks to be executed: [task ':jmeterRun']
:jmeterRun (Thread[main,5,main]) started.
:jmeterRun
Executing task ':jmeterRun' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
jmeter home is set ot /home/astoisavljevic/work-home/gradle-jmeter/workspace/gradle-jmeter/build/jmeter
:jmeterRun FAILED
:jmeterRun (Thread[main,5,main]) completed. Took 0.447 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jmeterRun'.
> Something goes wrong when we execute jmeter test.... Please see jmeter logs for more information

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 4.558 secs
Stopped 0 compiler daemon(s).

```

Maybe you have some idea what is wrong here?

Thank You

**Comment by staleks** [comment]
If I execute this task from Eclipse IDE,

here is the "Details log"

```
Something goes wrong when we execute jmeter test.... Please see jmeter logs for more information
Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.2.1-bin.zip'.
```
I am pretty sure that I don't have Gradle 2.2.1.

As I said previously, I am using Gradle 2.3 

```
astoisavljevic@astoisavljevic-laptop:~/work-home/gradle-jmeter/workspace/gradle-jmeter$ gradle -v

------------------------------------------------------------
Gradle 2.3
------------------------------------------------------------

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_75 (Oracle Corporation 24.75-b04)
OS:           Linux 3.13.0-48-generic amd64
```

That might put some light on the problem :)

Thank You

**Comment by foragerr** [comment]
Ah I see, the releases page needs to be updated.

> Something goes wrong when we execute jmeter test.... Please see jmeter logs for more information

The problem isn't the plugin anymore, its jmeter :) This plugin runs jmeter as a separate process, jmeter logs aren't show in the build output. You should look at the jmeter log, I believe the default location is `projectfolder/build/jmeter`.

**Comment by staleks** [comment]
>You should look at the jmeter log, I believe the default location is projectfolder/build/jmeter.

Does it means that I need to have jmeter installed in 
projectFolder/build/jmeter ?

**Comment by foragerr** [comment]
No, the plugin created the folder

**Comment by staleks** [comment]
You are right,

there is folder projectFolder/build/jmeter created.

And plugin creates ext and junit folders in jmeter. And further more there are two properties files
saveservice.properties and upgrade.properties. But nothing more :(

I think that problem still is in this error log

```
Something goes wrong when we execute jmeter test.... Please see jmeter logs for more information
Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.2.1-bin.zip'.
```

**Comment by djangofan** [comment]
Nice to see you guys working on this.  I searched Maven central and the latest  version of this plugin that I see is 1.3.2-2.9 ( http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jmeter-gradle-plugin%22 ) .  Shouldn't I see a version number like 1.3.3-2.13? This fix was opened in July 2014, after 1.3.2 was released so shouldn't the next version we get have a 1.3.3 on it?

**Comment by foragerr** [comment]
@djangofan you're right, I believe we need @kulya to perform releases.
Meanwhile, you can always build from source :)

**Comment by staleks** [comment]
OK, sorry for delay, but I had some "burning" issues on my daytime project :)

Now, I've cloned repository, build from source and got following artifacts in ${PROJECT_HOME}/build/libs folder:
- jmeter-gradle-plugin-1.3.3-2.13-SNAPSHOT.jar,
- jmeter-gradle-plugin-1.3.3-2.13-SNAPSHOT-javadoc.jar and
- jmeter-gradle-plugin-1.3.3-2.13-SNAPSHOT-sources.jar

Can you help me now how to integrate this version now in my project build script ?

Thank You

**Comment by staleks** [comment]
Following "Maven logic" (as I am coming from this world and I am new to Gradle), I guess that 
I need to have this JAR in ~/.m2/repository (then I can have mavenLocal() as repository for this plugin)

But building this project from source, doesn't generate pom.xml and I am afraid that just placing this JAR 
"jmeter-gradle-plugin-1.3.3-2.13-SNAPSHOT.jar" in ~/.m2/repostiory/com/github/kulya/jmeter-gradle-plugin/1.3.3-2.13-SNAPSHOT without having proper pom.xml 

won't work for me.

Any suggestions ?

Thank You

**Comment by foragerr** [comment]
@staleks 1.3.3 and 1.3.4 binaries are now built and published to maven central - except it may take some time for them to appear there. Meanwhile you can use them from this maven repo: https://oss.sonatype.org/content/groups/public

1.3.3 has a different defect, you should use 1.3.4

If you still want to build from source, you can add `apply plugin: 'maven'` to your build.gradle file and then you would be able to run task `gradle install` to push jars and poms correctly to your local repo.

**Comment by staleks** [comment]
Ok, this seems working :)

just for future users:

buildscript section:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "com.github.kulya:jmeter-gradle-plugin:1.3.4-2.13"
    }
}
```

and repostiories:

```
repositories {
    mavenCentral()
    maven {
        url "https://oss.sonatype.org/content/groups/public"
    }
}
```

At least until this version is publicly available on Maven Central.

Thnx for support.

**Comment by staleks** [comment]
Now I have other problem with jmeter report in HTML format. 

But let's open another issue for this.

NOTE: this one can be closed, since starting problem is not more an issue.

Thnx

**Comment by jk1** [comment]
I'm facing the same problem with 1.3.4-2.13 and gradle 2.3. My buildscript is as follows:

```
apply plugin: 'jmeter'

buildscript {
    repositories {mavenCentral()}

    dependencies {
        classpath "com.github.kulya:jmeter-gradle-plugin:1.3.4-2.13"
    }
}

jmeterRun.configure {
     jmeterTestFiles = [file("req.jmx")]
 }

```

Running ./gradlew jmeterRun returns only "Something went wrong during jmeter test execution, Please see jmeter logs for more information" with no actual log to look into. Interestingly, jmeterListTestPlan works:

```
:testing:jmeterListTestPlan

Jmeter Test Plan
----------------
req.jmx

BUILD SUCCESSFUL
```

**Comment by foragerr** [comment]
@jk1 Where is your `req.jmx` file located? If it is in `/src/test/jmeter`, then can you please comment out the `jmeterTestFiles =` line in your build.gradle?

**Comment by jk1** [comment]
@foragerr, thanks for looking into this. I've tried with `jmeterTestFiles = ...` line removed, but it doesn't seem to make any difference. Here's the minimal example, that reproduces the problem in my environment: https://github.com/jk1/Jmeter-plugin-demo

**Comment by foragerr** [comment]
@jk1 Thank for the minimal example, certainly makes debugging easier :)

I ran jmeterrun on your example and got this:

```
java.lang.RuntimeException: Could not read JMeter properties file:\src\test\jmeter\jmeter.properties
    at org.apache.jmeter.util.JMeterUtils.loadJMeterProperties(JMeterUtils.java:193)
    at org.apache.jmeter.JMeter.initializeProperties(JMeter.java:527)
    at org.apache.jmeter.JMeter.start(JMeter.java:299)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.jmeter.NewDriver.main(NewDriver.java:264)
An error occurred: Could not read JMeter properties file:\src\test\jmeter\jmeter.properties
:jmeterRun FAILED

FAILURE: Build failed with an exception.
```

This is a known issue #38 , fix is waiting for a pull request #47 to be accepted. 

The workaround is to add a  jmeter.properties file in either `/src/test/jmeter` or using `jmeterPropertyFile` setting, to point to a properties file. Even a blank properties file is fine.

I'm more curious about why you didn't see the error stack trace when _you_ ran jmeterRun. try running gradle with --info or --debug?

**Comment by jk1** [comment]
@foragerr, that's a good question. I've tried the same code in a clean virtual environment and it works exactly as you're describing, printing:

```
java.lang.RuntimeException: Could not read JMeter properties file:/home/user/test/jmeter.properties
        at org.apache.jmeter.util.JMeterUtils.loadJMeterProperties(JMeterUtils.java:193)
        at org.apache.jmeter.JMeter.initializeProperties(JMeter.java:527)
        at org.apache.jmeter.JMeter.start(JMeter.java:299)

```

so I suppose it's an issue with my laptop or OS configuration and not with the plugin. 
Thanks a lot for your helpful advice, with jmeter.properties in place it seems to be working quite fine.
